### ISSUE TITLE
Is this for common Chatglm or 智谱AI? 

### ISSUE THREAD

**Issue by bjwswang** [sunny0826/go-chatglm#2]
Hi @sunny0826  Great job! 
It's really glad to see that someone has been doing the same thing. As you konw, almost all AI tools are written in Python which makes it so difficult to use AI in Cloud Native projects. 
I am doing the same thing(Using AI in go) at https://github.com/kubeagi/arcadia . Just finished a lib to use `智谱AI` in Golang
https://github.com/kubeagi/arcadia/tree/main/pkg/llms/zhipuai

**Comment by bjwswang** [comment]
Seems we both use 智谱AI but `apis` has changed...

**Comment by sunny0826** [comment]
ops, I was about to update it.
